In [27]:
# =========================================================
# Import Required Libraries
# =========================================================
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers
import pandas as pd

In [28]:
# =========================================================
# Dataset
# =========================================================
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
                      0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,
                      35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,
                       12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,
                    0, 1, 0, 1, 0, 0, 1, 1]
})

In [29]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [30]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [31]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df['needs_water']

In [32]:
X_min = X.min()
X_max = X.max()
X_scaled = (X - X_min) / (X_max - X_min + 1e-8)

In [33]:
X_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [34]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.25, random_state=42, stratify=y
)

In [35]:
model = keras.Sequential([
    layers.Input(shape= (X_train.shape[1],)),
    layers.Dense(8,activation= 'relu'),
    layers.Dense(1,activation = 'sigmoid')
])

In [36]:
model.compile(optimizer='sgd',loss = 'binary_crossentropy',metrics= ['accuracy'])

In [37]:
history = model.fit(
    X_train.values, y_train.values, 
    validation_data = (X_test.values, y_test.values),
    epochs=100, batch_size=4, verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 139ms/step - accuracy: 0.6667 - loss: 0.5907 - val_accuracy: 0.5000 - val_loss: 0.6262
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5886 - val_accuracy: 0.5000 - val_loss: 0.6241
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.5865 - val_accuracy: 0.5000 - val_loss: 0.6220
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5842 - val_accuracy: 0.5000 - val_loss: 0.6199
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5815 - val_accuracy: 0.5000 - val_loss: 0.6179
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.5797 - val_accuracy: 0.5000 - val_loss: 0.6160
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.5782 - val_accuracy: 0.5000 - val_loss: 0.6141
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.5761 - val_accuracy: 0.5000 - val_loss: 0.6123
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5773 - val_accuracy: 0.5000 - val_loss: 0.6106
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6667 - loss: 0.5734 - val_accuracy: 0.5000 - val_loss: 0.6089
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6667 - loss: 0.5735 - val_accuracy: 0.5000 - val_loss: 0.6073
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6667 - loss: 0.5710 - val_accuracy: 0.5000 - val_loss: 0.6057
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.5695 - val_accuracy: 0.5000 - val_loss: 0.6042
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5678 - val_accuracy: 0.5000 - val_loss: 0.6027
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.5659 - val_accuracy: 0.5000 - val_loss: 0.6012
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.5668 - val_accuracy: 0.5000 - val_loss: 0.5998
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6667 - loss: 0.5655 - val_accuracy: 0.5000 - val_loss: 0.5984
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.7500 - loss: 0.5630 - val_accuracy: 0.7500 - val_loss: 0.5971
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.7500 - loss: 0.5618 - val_accuracy: 0.7500 - val_loss: 0.5957
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.7500 - loss: 0.5602 - val_accuracy: 0.7500 - val_loss: 0.5945
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.7500 - loss: 0.5607 - val_accuracy: 1.0000 - val_loss: 0.5933
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5587 - val_accuracy: 1.0000 - val_loss: 0.5920
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.7500 - loss: 0.5577 - val_accuracy: 1.0000 - val_loss: 0.5909
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5564 - val_accuracy: 1.0000 - val_loss: 0.5897
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.8333 - loss: 0.5574 - val_accuracy: 1.0000 - val_loss: 0.5885
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.8333 - loss: 0.5548 - val_accuracy: 1.0000 - val_loss: 0.5874
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8333 - loss: 0.5541 - val_accuracy: 1.0000 - val_loss: 0.5863
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.8333 - loss: 0.5532 - val_accuracy: 1.0000 - val_loss: 0.5852
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.8333 - loss: 0.5549 - val_accuracy: 1.0000 - val_loss: 0.5841
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.5516 - val_accuracy: 1.0000 - val_loss: 0.5831
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8333 - loss: 0.5509 - val_accuracy: 1.0000 - val_loss: 0.5820
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.8333 - loss: 0.5520 - val_accuracy: 1.0000 - val_loss: 0.5810
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.8333 - loss: 0.5485 - val_accuracy: 1.0000 - val_loss: 0.5801
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.8333 - loss: 0.5473 - val_accuracy: 1.0000 - val_loss: 0.5791
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.8333 - loss: 0.5498 - val_accuracy: 1.0000 - val_loss: 0.5782
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9167 - loss: 0.5461 - val_accuracy: 1.0000 - val_loss: 0.5773
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.5457 - val_accuracy: 1.0000 - val_loss: 0.5764
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.5450 - val_accuracy: 1.0000 - val_loss: 0.5755
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5442 - val_accuracy: 1.0000 - val_loss: 0.5746
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.5457 - val_accuracy: 1.0000 - val_loss: 0.5737
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5420 - val_accuracy: 1.0000 - val_loss: 0.5729
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5413 - val_accuracy: 1.0000 - val_loss: 0.5720
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.5413 - val_accuracy: 1.0000 - val_loss: 0.5712
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.5398 - val_accuracy: 1.0000 - val_loss: 0.5703
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.5418 - val_accuracy: 1.0000 - val_loss: 0.5695
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.5392 - val_accuracy: 1.0000 - val_loss: 0.5687
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5382 - val_accuracy: 1.0000 - val_loss: 0.5679
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5374 - val_accuracy: 1.0000 - val_loss: 0.5671
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 1.0000 - loss: 0.5375 - val_accuracy: 1.0000 - val_loss: 0.5663
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.5356 - val_accuracy: 1.0000 - val_loss: 0.5655
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5354 - val_accuracy: 1.0000 - val_loss: 0.5647
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.5352 - val_accuracy: 1.0000 - val_loss: 0.5639
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.5341 - val_accuracy: 1.0000 - val_loss: 0.5632
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.5337 - val_accuracy: 1.0000 - val_loss: 0.5624
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.5326 - val_accuracy: 1.0000 - val_loss: 0.5617
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.5314 - val_accuracy: 1.0000 - val_loss: 0.5609
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.5307 - val_accuracy: 1.0000 - val_loss: 0.5602
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.5308 - val_accuracy: 1.0000 - val_loss: 0.5594
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.5303 - val_accuracy: 1.0000 - val_loss: 0.5587
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5293 - val_accuracy: 1.0000 - val_loss: 0.5579
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.5288 - val_accuracy: 1.0000 - val_loss: 0.5572
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.5279 - val_accuracy: 1.0000 - val_loss: 0.5565
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5274 - val_accuracy: 1.0000 - val_loss: 0.5558
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.5264 - val_accuracy: 1.0000 - val_loss: 0.5550
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5259 - val_accuracy: 1.0000 - val_loss: 0.5543
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5255 - val_accuracy: 1.0000 - val_loss: 0.5536
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5241 - val_accuracy: 1.0000 - val_loss: 0.5529
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.5233 - val_accuracy: 1.0000 - val_loss: 0.5522
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.5230 - val_accuracy: 1.0000 - val_loss: 0.5515
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.5220 - val_accuracy: 1.0000 - val_loss: 0.5508
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5222 - val_accuracy: 1.0000 - val_loss: 0.5501
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9167 - loss: 0.5213 - val_accuracy: 1.0000 - val_loss: 0.5494
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.5208 - val_accuracy: 1.0000 - val_loss: 0.5487
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5204 - val_accuracy: 1.0000 - val_loss: 0.5481
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5189 - val_accuracy: 1.0000 - val_loss: 0.5474
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.5182 - val_accuracy: 1.0000 - val_loss: 0.5467
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5174 - val_accuracy: 1.0000 - val_loss: 0.5460
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.5173 - val_accuracy: 1.0000 - val_loss: 0.5453
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5183 - val_accuracy: 1.0000 - val_loss: 0.5447
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5177 - val_accuracy: 1.0000 - val_loss: 0.5440
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.5155 - val_accuracy: 1.0000 - val_loss: 0.5433
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.5144 - val_accuracy: 1.0000 - val_loss: 0.5426
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.5138 - val_accuracy: 1.0000 - val_loss: 0.5420
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5144 - val_accuracy: 1.0000 - val_loss: 0.5413
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.5140 - val_accuracy: 1.0000 - val_loss: 0.5406
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5112 - val_accuracy: 1.0000 - val_loss: 0.5400
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.5112 - val_accuracy: 1.0000 - val_loss: 0.5393
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5099 - val_accuracy: 1.0000 - val_loss: 0.5386
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.5124 - val_accuracy: 1.0000 - val_loss: 0.5380
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5092 - val_accuracy: 1.0000 - val_loss: 0.5374
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5087 - val_accuracy: 1.0000 - val_loss: 0.5367
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.5072 - val_accuracy: 1.0000 - val_loss: 0.5361
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.5076 - val_accuracy: 1.0000 - val_loss: 0.5354
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.5069 - val_accuracy: 1.0000 - val_loss: 0.5347
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.9167 - loss: 0.5060 - val_accuracy: 1.0000 - val_loss: 0.5341
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.5045 - val_accuracy: 1.0000 - val_loss: 0.5334
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.5038 - val_accuracy: 1.0000 - val_loss: 0.5327
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.5031 - val_accuracy: 1.0000 - val_loss: 0.5320
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.5037 - val_accuracy: 1.0000 - val_loss: 0.5313
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.5041 - val_accuracy: 1.0000 - val_loss: 0.5307